services:
  tarantool-router-msk:
    image: tarantooldb:2x-latest
    networks:
      - tarantooldb_network
    ports:
      - "3301:3301"
    volumes:
      - ../certs:/tmp/certs
    environment:
      - TT_INSTANCE_NAME=router-msk
      - TT_CONFIG_ETCD_ENDPOINTS=http://etcd1:2379,http://etcd2:2379,http://etcd3:2379
      - TT_CONFIG_ETCD_PREFIX=/tdb
      - TT_CONFIG_ETCD_HTTP_REQUEST_TIMEOUT=3

  tarantool-storage-1-msk:
    image: tarantooldb:2x-latest
    networks:
      - tarantooldb_network
    ports:
      - "3303:3301"
    volumes:
      - ../certs:/tmp/certs
    environment:
      - TT_INSTANCE_NAME=storage-1-msk
      - TT_CONFIG_ETCD_ENDPOINTS=http://etcd1:2379,http://etcd2:2379,http://etcd3:2379
      - TT_CONFIG_ETCD_PREFIX=/tdb
      - TT_CONFIG_ETCD_HTTP_REQUEST_TIMEOUT=3
  tarantool-storage-1-spb:
    image: tarantooldb:2x-latest
    networks:
      - tarantooldb_network
    ports:
      - "3304:3301"
    volumes:
      - ../certs:/tmp/certs
    environment:
      - TT_INSTANCE_NAME=storage-1-spb
      - TT_CONFIG_ETCD_ENDPOINTS=http://etcd1:2379,http://etcd2:2379,http://etcd3:2379
      - TT_CONFIG_ETCD_PREFIX=/tdb
      - TT_CONFIG_ETCD_HTTP_REQUEST_TIMEOUT=3

  init_host:
    image: tarantooldb:2x-latest
    networks:
      - tarantooldb_network
    volumes:
      - ./migrations/:/app/tarantooldb/migrations/
      - ../certs:/tmp/certs
    depends_on:
      - tarantool-router-msk
      - tarantool-storage-1-msk
      - tarantool-storage-1-spb
    environment:
      - TT_CLI_USERNAME=admin
      - TT_CLI_PASSWORD=secret-cluster-cookie
      - TT_CLI_SSLKEYFILE=/tmp/certs/client-key.pem
      - TT_CLI_SSLCERTFILE=/tmp/certs/client-cert.pem
    command: /bin/sh -c "\
        tools/client/wait_instance_ready.sh 15 tarantool-router-msk:3301 \
        && tools/client/wait_instance_ready.sh 15 tarantool-storage-1-msk:3301 \
        && tools/client/wait_instance_ready.sh 15 tarantool-storage-1-spb:3301 \
        && tt replicaset vshard bootstrap \
            --sslkeyfile /tmp/certs/client-key.pem \
            --sslcertfile /tmp/certs/client-cert.pem \
            tarantool-router-msk:3301 \
        && tt migrations publish http://etcd1:2379/tdb migrations \
        && tt migrations apply \
            --tarantool-sslkeyfile /tmp/certs/client-key.pem \
            --tarantool-sslcertfile /tmp/certs/client-cert.pem \
            http://etcd1:2379/tdb \
        && echo Initialize has completed successfully."

networks:
  tarantooldb_network:
    external: true
