x-common: &common
  image: tarantooldb:3x-latest
  networks:
    - tarantooldb_network
  volumes:
    - ../certs/ca:/certs/ca:ro
    - ../certs/tarantool:/certs/tarantool:ro
    - ../certs/etcd:/certs/etcd:ro

x-common-env: &common-env
  TT_CONFIG_ETCD_ENDPOINTS: https://etcd1:2379,https://etcd2:2379,https://etcd3:2379
  TT_CONFIG_ETCD_PREFIX: /tdb
  TT_CONFIG_ETCD_HTTP_REQUEST_TIMEOUT: 3
  TT_CONFIG_ETCD_SSL_CA_FILE: /certs/ca/root-ca.pem
  TT_CONFIG_ETCD_SSL_SSL_CERT: /certs/etcd/client.pem
  TT_CONFIG_ETCD_SSL_SSL_KEY: /certs/etcd/client-key.pem

services:
  tarantool-router-msk:
    <<: *common
    ports:
      - "3301:3301"
    environment:
      <<: *common-env
      TT_INSTANCE_NAME: router-msk

  tarantool-storage-1-msk:
    <<: *common
    ports:
      - "3302:3301"
    environment:
      <<: *common-env
      TT_INSTANCE_NAME: storage-1-msk

  tarantool-storage-1-spb:
    <<: *common
    ports:
      - "3303:3301"
    environment:
      <<: *common-env
      TT_INSTANCE_NAME: storage-1-spb

  init_host:
    image: tarantooldb:3x-latest
    networks:
      - tarantooldb_network
    volumes:
      - ./migrations/:/app/tarantooldb/migrations/
      - ../certs/ca:/certs/ca:ro
      - ../certs/tarantool:/certs/tarantool:ro
      - ../certs/etcd:/certs/etcd:ro
    depends_on:
      - tarantool-router-msk
      - tarantool-storage-1-msk
      - tarantool-storage-1-spb
    environment:
      - TT_CLI_USERNAME=admin
      - TT_CLI_PASSWORD=secret-cluster-cookie
      - TT_CLI_SSLKEYFILE=/certs/tarantool/client-key.pem
      - TT_CLI_SSLCERTFILE=/certs/tarantool/client.pem
    command:
      - /bin/sh
      - -c
      - |
        echo '[1] Waiting for tarantool-router-msk...' &&
        tools/client/wait_instance_ready.sh 30 tarantool-router-msk:3301 &&
        echo '[2] Waiting for tarantool-storage-1-msk...' &&
        tools/client/wait_instance_ready.sh 30 tarantool-storage-1-msk:3301 &&
        echo '[3] Waiting for tarantool-storage-1-spb...' &&
        tools/client/wait_instance_ready.sh 30 tarantool-storage-1-spb:3301 &&
        echo '[4] Bootstrapping vshard...' &&
        tt replicaset vshard bootstrap \
          --sslkeyfile /certs/tarantool/client-key.pem \
          --sslcertfile /certs/tarantool/client.pem \
          tarantool-router-msk:3301 &&
        echo '[5] Publishing migrations...' &&
        tt migrations publish \
          'https://etcd1:2379/tdb?ssl_ca_file=/certs/ca/root-ca.pem&ssl_cert_file=/certs/etcd/client.pem&ssl_key_file=/certs/etcd/client-key.pem' \
          migrations &&
        echo '[6] Applying migrations...' &&
        tt migrations apply \
          --tarantool-sslkeyfile /certs/tarantool/client-key.pem \
          --tarantool-sslcertfile /certs/tarantool/client.pem \
          'https://etcd1:2379/tdb?ssl_ca_file=/certs/ca/root-ca.pem&ssl_cert_file=/certs/etcd/client.pem&ssl_key_file=/certs/etcd/client-key.pem' &&
        echo 'Initialize has completed successfully.'

networks:
  tarantooldb_network:
    external: true
