version: '3'
services:
  tarantool-router-msk:
    image: tarantooldb:latest
    networks:
      - tarantooldb_network
    ports:
      - "8081:8081"
      - "3301:3301"
    environment:
      - TARANTOOL_ADVERTISE_URI=tarantool-router-msk:3301
      - TARANTOOL_ALIAS=router-msk
  tarantool-router-spb:
    image: tarantooldb:latest
    networks:
      - tarantooldb_network
    ports:
      - "8082:8081"
      - "3302:3301"
    environment:
      - TARANTOOL_ADVERTISE_URI=tarantool-router-spb:3301
      - TARANTOOL_ALIAS=router-spb
  tarantool-storage-1-msk:
    image: tarantooldb:latest
    networks:
      - tarantooldb_network
    ports:
      - "8083:8081"
      - "3303:3301"
    environment:
      - TARANTOOL_ADVERTISE_URI=tarantool-storage-1-msk:3301
      - TARANTOOL_ALIAS=storage-1-msk
  tarantool-storage-1-spb:
    image: tarantooldb:latest
    networks:
      - tarantooldb_network
    ports:
      - "8084:8081"
      - "3304:3301"
    environment:
      - TARANTOOL_ADVERTISE_URI=tarantool-storage-1-spb:3301
      - TARANTOOL_ALIAS=storage-1-spb
  tarantool-storage-2-msk:
    image: tarantooldb:latest
    networks:
      - tarantooldb_network
    ports:
      - "8085:8081"
      - "3305:3301"
    environment:
      - TARANTOOL_ADVERTISE_URI=tarantool-storage-2-msk:3301
      - TARANTOOL_ALIAS=storage-2-msk
  tarantool-storage-2-spb:
    image: tarantooldb:latest
    networks:
      - tarantooldb_network
    ports:
      - "8086:8081"
      - "3306:3301"
    environment:
      - TARANTOOL_ADVERTISE_URI=tarantool-storage-2-spb:3301
      - TARANTOOL_ALIAS=storage-2-spb
  etcd1:
    image: quay.io/coreos/etcd:v3.4.0
    command: etcd --name etcd1 --advertise-client-urls http://etcd1:2379 --listen-client-urls http://0.0.0.0:2379 --initial-advertise-peer-urls http://etcd1:2380 --listen-peer-urls http://0.0.0.0:2380 --initial-cluster-token etcd-cluster --initial-cluster etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380 --initial-cluster-state new --enable-v2
    ports:
      - "12379:2379"
      - "12380:2380"
    networks:
      - tarantooldb_network
  etcd2:
    image: quay.io/coreos/etcd:v3.4.0
    command: etcd --name etcd2 --advertise-client-urls http://etcd2:2379 --listen-client-urls http://0.0.0.0:2379 --initial-advertise-peer-urls http://etcd2:2380 --listen-peer-urls http://0.0.0.0:2380 --initial-cluster-token etcd-cluster --initial-cluster etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380 --initial-cluster-state new --enable-v2
    ports:
      - "22379:2379"
      - "22380:2380"
    networks:
      - tarantooldb_network
  etcd3:
    image: quay.io/coreos/etcd:v3.4.0
    command: etcd --name etcd3 --advertise-client-urls http://etcd3:2379 --listen-client-urls http://0.0.0.0:2379 --initial-advertise-peer-urls http://etcd3:2380 --listen-peer-urls http://0.0.0.0:2380 --initial-cluster-token etcd-cluster --initial-cluster etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380 --initial-cluster-state new --enable-v2
    ports:
      - "32379:2379"
      - "32380:2380"
    networks:
      - tarantooldb_network
  user-host:
    image: tarantooldb:latest
    networks:
      - tarantooldb_network
    environment:
      - TARANTOOLDB_TARGET_URI=tarantool-router-msk:8081
      - BOOTSTRAP_FAILOVER=1
    working_dir: /usr/share/tarantool/tarantooldb/client/utils/
    command: /bin/sh -c "./bootstrap.sh && ./health_check.sh && ./migrate.sh"
    depends_on:
      - tarantool-router-msk
      - tarantool-router-spb
      - tarantool-storage-1-msk
      - tarantool-storage-1-spb
      - tarantool-storage-2-msk
      - tarantool-storage-2-spb
      - etcd1
      - etcd2
      - etcd3
    volumes:
      - ./bootstrap/:/bootstrap/
networks:
  tarantooldb_network:
