version: '3'
services:
  tracing:
    image: "jaegertracing/all-in-one:1.53"
    networks:
      - "tarantooldb_network"
    ports:
      - "16686:16686"
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: ":9411"

  tarantool-router:
    image: "tarantooldb:2x-latest"
    networks:
      - "tarantooldb_network"
    ports:
      - "8080:8081"
      - "3300:3301"
    environment:
      - "TARANTOOL_ADVERTISE_URI=tarantool-router:3301"

  tarantool-storage:
    image: "tarantooldb:2x-latest"
    networks:
      - "tarantooldb_network"
    ports:
      - "8081:8081"
      - "3301:3301"
    environment:
      - "TARANTOOL_ADVERTISE_URI=tarantool-storage:3301"

  tarantool-db-init:
    image: "tarantooldb:2x-latest"
    networks:
      - "tarantooldb_network"
    environment:
      - "TARANTOOLDB_TARGET_URI=tarantool-router:8081"
    working_dir: "/app/tarantooldb/client/utils/"
    command: '/bin/bash -c "./bootstrap.sh && ./health_check.sh && ./migrate.sh"'
    depends_on:
      - "tarantool-router"
      - "tarantool-storage"
    volumes:
      - "./bootstrap/:/bootstrap/"

networks:
  tarantooldb_network:
