services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.15
    command: >
      etcd --name etcd
      --advertise-client-urls http://etcd:2379
      --listen-client-urls http://0.0.0.0:2379
      --initial-advertise-peer-urls http://etcd:2380
      --listen-peer-urls http://0.0.0.0:2380
      --initial-cluster etcd=http://etcd:2380
      --initial-cluster-state new
    networks:
      - grpc_example

  tcm:
    image: ${TDB_IMAGE:-tarantooldb:3x-latest}
    networks:
      - grpc_example
    ports:
      - "127.0.0.1:${TCM_HOST_PORT:-8081}:8081"
    volumes:
      - ./tcm.yml:/app/tarantooldb/tcm.yml:ro
      - ../cluster/config.yml:/app/tarantooldb/config.yml:ro
    command: ["./tcm", "-c", "tcm.yml"]

networks:
  grpc_example:
    name: tdb_grpc_example_network
    external: true
