version: '3'
services:
  tarantool-router:
    image: tarantooldb:1x-latest
    networks:
      - tarantooldb_network
    ports:
      - "8080:8081"
      - "3300:3301"
    environment:
      - TARANTOOL_ADVERTISE_URI=tarantool-router:3301
      - TARANTOOL_ALIAS=router-1
  tarantool-storage1:
    image: tarantooldb:1x-latest
    networks:
      - tarantooldb_network
    ports:
      - "8081:8081"
      - "3301:3301"
    environment:
      - TARANTOOL_ADVERTISE_URI=tarantool-storage1:3301
      - TARANTOOL_ALIAS=storage-A-1
  tarantool-storage2:
    image: tarantooldb:1x-latest
    networks:
      - tarantooldb_network
    ports:
      - "8082:8081"
      - "3302:3301"
    environment:
      - TARANTOOL_ADVERTISE_URI=tarantool-storage2:3301
      - TARANTOOL_ALIAS=storage-A-2
  tarantool-storage3:
    image: tarantooldb:1x-latest
    networks:
      - tarantooldb_network
    ports:
      - "8083:8081"
      - "3303:3301"
    environment:
      - TARANTOOL_ADVERTISE_URI=tarantool-storage3:3301
      - TARANTOOL_ALIAS=storage-B-1
  tarantool-storage4:
    image: tarantooldb:1x-latest
    networks:
      - tarantooldb_network
    ports:
      - "8084:8081"
      - "3304:3301"
    environment:
      - TARANTOOL_ADVERTISE_URI=tarantool-storage4:3301
      - TARANTOOL_ALIAS=storage-B-2
  user-host:
    image: tarantooldb:1x-latest
    networks:
      - tarantooldb_network
    environment:
      - TARANTOOLDB_TARGET_URI=tarantool-router:8081
    working_dir: /usr/share/tarantool/tarantooldb/tools/client/
    command: /bin/sh -c "./bootstrap.sh && ./health_check.sh && ./migrate.sh"
    depends_on:
      - tarantool-router
      - tarantool-storage1
      - tarantool-storage2
      - tarantool-storage3
      - tarantool-storage4
    volumes:
      - ./bootstrap/:/bootstrap/
networks:
  tarantooldb_network:
