services:
  tarantool-router-msk:
    image: tarantooldb:latest
    networks:
      - tarantooldb_network
    ports:
      - "3301:3301"
    environment:
      - TT_INSTANCE_NAME=router-msk
      - TT_CONFIG_STORAGE_ENDPOINTS=[{"uri":"tarantool-config-storage-1:3301","login":"client","password":"secret"},{"uri":"tarantool-config-storage-2:3301","login":"client","password":"secret"},{"uri":"tarantool-config-storage-3:3301","login":"client","password":"secret"}]
      - TT_CONFIG_STORAGE_PREFIX=/tdb
  tarantool-router-spb:
    image: tarantooldb:latest
    networks:
      - tarantooldb_network
    ports:
      - "3302:3301"
    environment:
      - TT_INSTANCE_NAME=router-spb
      - TT_CONFIG_STORAGE_ENDPOINTS=[{"uri":"tarantool-config-storage-1:3301","login":"client","password":"secret"},{"uri":"tarantool-config-storage-2:3301","login":"client","password":"secret"},{"uri":"tarantool-config-storage-3:3301","login":"client","password":"secret"}]
      - TT_CONFIG_STORAGE_PREFIX=/tdb
  tarantool-storage-1-msk:
    image: tarantooldb:latest
    networks:
      - tarantooldb_network
    ports:
      - "3303:3301"
    environment:
      - TT_INSTANCE_NAME=storage-1-msk
      - TT_CONFIG_STORAGE_ENDPOINTS=[{"uri":"tarantool-config-storage-1:3301","login":"client","password":"secret"},{"uri":"tarantool-config-storage-2:3301","login":"client","password":"secret"},{"uri":"tarantool-config-storage-3:3301","login":"client","password":"secret"}]
      - TT_CONFIG_STORAGE_PREFIX=/tdb
  tarantool-storage-1-spb:
    image: tarantooldb:latest
    networks:
      - tarantooldb_network
    ports:
      - "3304:3301"
    environment:
      - TT_INSTANCE_NAME=storage-1-spb
      - TT_CONFIG_STORAGE_ENDPOINTS=[{"uri":"tarantool-config-storage-1:3301","login":"client","password":"secret"},{"uri":"tarantool-config-storage-2:3301","login":"client","password":"secret"},{"uri":"tarantool-config-storage-3:3301","login":"client","password":"secret"}]
      - TT_CONFIG_STORAGE_PREFIX=/tdb
  tarantool-storage-1-brn:
    image: tarantooldb:latest
    networks:
      - tarantooldb_network
    ports:
      - "3305:3301"
    environment:
      - TT_INSTANCE_NAME=storage-1-brn
      - TT_CONFIG_STORAGE_ENDPOINTS=[{"uri":"tarantool-config-storage-1:3301","login":"client","password":"secret"},{"uri":"tarantool-config-storage-2:3301","login":"client","password":"secret"},{"uri":"tarantool-config-storage-3:3301","login":"client","password":"secret"}]
      - TT_CONFIG_STORAGE_PREFIX=/tdb
  tarantool-storage-2-msk:
    image: tarantooldb:latest
    networks:
      - tarantooldb_network
    ports:
      - "3306:3301"
    environment:
      - TT_INSTANCE_NAME=storage-2-msk
      - TT_CONFIG_STORAGE_ENDPOINTS=[{"uri":"tarantool-config-storage-1:3301","login":"client","password":"secret"},{"uri":"tarantool-config-storage-2:3301","login":"client","password":"secret"},{"uri":"tarantool-config-storage-3:3301","login":"client","password":"secret"}]
      - TT_CONFIG_STORAGE_PREFIX=/tdb
  tarantool-storage-2-spb:
    image: tarantooldb:latest
    networks:
      - tarantooldb_network
    ports:
      - "3307:3301"
    environment:
      - TT_INSTANCE_NAME=storage-2-spb
      - TT_CONFIG_STORAGE_ENDPOINTS=[{"uri":"tarantool-config-storage-1:3301","login":"client","password":"secret"},{"uri":"tarantool-config-storage-2:3301","login":"client","password":"secret"},{"uri":"tarantool-config-storage-3:3301","login":"client","password":"secret"}]
      - TT_CONFIG_STORAGE_PREFIX=/tdb
  tarantool-storage-2-brn:
    image: tarantooldb:latest
    networks:
      - tarantooldb_network
    ports:
      - "3308:3301"
    environment:
      - TT_INSTANCE_NAME=storage-2-brn
      - TT_CONFIG_STORAGE_ENDPOINTS=[{"uri":"tarantool-config-storage-1:3301","login":"client","password":"secret"},{"uri":"tarantool-config-storage-2:3301","login":"client","password":"secret"},{"uri":"tarantool-config-storage-3:3301","login":"client","password":"secret"}]
      - TT_CONFIG_STORAGE_PREFIX=/tdb

networks:
  tarantooldb_network:
    external: true
