services:
  load_config:
    image: tarantooldb:latest
    networks:
      - tarantooldb_network
    volumes:
      - ./config.yml:/app/tarantooldb/config.yml
    environment:
      - TT_CLI_USERNAME=client
      - TT_CLI_PASSWORD=secret
    command: |
      /bin/bash -c "
        (
        (echo Try tarantool-config-storage-1 && tt cluster publish http://tarantool-config-storage-1:3301/tdb config.yml --force) ||
        (echo Try tarantool-config-storage-2 && tt cluster publish http://tarantool-config-storage-2:3301/tdb config.yml --force) ||
        (echo Try tarantool-config-storage-3 && tt cluster publish http://tarantool-config-storage-3:3301/tdb config.yml --force)
        ) && echo Config loaded
      "

networks:
  tarantooldb_network:
    external: true
