credentials:
  users:
    admin:
      password: 'secret-cluster-cookie'
      roles: [super]

iproto:
  advertise:
    peer:
      login: admin

replication:
  failover: off

database:
  mode: rw

groups:
  storages:
    replicasets:
      storage-1:
        instances:
          storage-1-msk:
            iproto:
              listen:
                - uri: tarantool-storage-1-msk:3301
              advertise:
                client: tarantool-storage-1-msk:3301
          storage-1-spb:
            iproto:
              listen:
                - uri: tarantool-storage-1-spb:3301
              advertise:
                client: tarantool-storage-1-spb:3301
          storage-1-brn:
            iproto:
              listen:
                - uri: tarantool-storage-1-brn:3301
              advertise:
                client: tarantool-storage-1-brn:3301
