services:
  tarantool-config-storage-1:
    image: tarantooldb:3x-latest
    networks:
      - tarantooldb_network
    ports:
      - "3401:3301"
    volumes:
      - ./config.yml:/app/tarantooldb/config.yml
    environment:
      - TT_INSTANCE_NAME=config-storage-1
      - TT_CONFIG=/app/tarantooldb/config.yml
  tarantool-config-storage-2:
    image: tarantooldb:3x-latest
    networks:
      - tarantooldb_network
    ports:
      - "3402:3301"
    volumes:
      - ./config.yml:/app/tarantooldb/config.yml
    environment:
      - TT_INSTANCE_NAME=config-storage-2
      - TT_CONFIG=/app/tarantooldb/config.yml
  tarantool-config-storage-3:
    image: tarantooldb:3x-latest
    networks:
      - tarantooldb_network
    ports:
      - "3403:3301"
    volumes:
      - ./config.yml:/app/tarantooldb/config.yml
    environment:
      - TT_INSTANCE_NAME=config-storage-3
      - TT_CONFIG=/app/tarantooldb/config.yml

networks:
  tarantooldb_network:
    external: true
