events {
    worker_connections  1024;
}

http {
    upstream backend {
        server tarantool-router1:8081;
        server tarantool-router2:8081;
    }

    server {
        listen 8000;
        location / {
            if ($http_authorization = '') {
                return 401;
            }
            if ($http_authorization != 'Bearer 123') {
                return 403;
            }

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_pass http://backend;
        }
    }
}
