version: '3'
services:
  tarantool-router-1:
    image: tarantooldb:latest
    networks:
      - tarantooldb_network
    ports:
      - "3301:3301"
    volumes:
      - ./config.yml:/usr/share/tarantool/tarantooldb/config.yml
      - ./migrations:/tmp/migrations
    environment:
      - TT_INSTANCE_NAME=router-1
      - TT_CONFIG=/usr/share/tarantool/tarantooldb/config.yml
    depends_on:
      - etcd1
      - etcd2
      - etcd3

  tarantool-storage-1:
    image: tarantooldb:latest
    networks:
      - tarantooldb_network
    ports:
      - "3303:3301"
    volumes:
      - ./config.yml:/usr/share/tarantool/tarantooldb/config.yml
    environment:
      - TT_INSTANCE_NAME=storage-1
      - TT_CONFIG=/usr/share/tarantool/tarantooldb/config.yml
    depends_on:
      - etcd1
      - etcd2
      - etcd3

  etcd1:
    image: quay.io/coreos/etcd:v3.4.0
    command: etcd --name etcd1 --advertise-client-urls http://etcd1:2379 --listen-client-urls http://0.0.0.0:2379 --initial-advertise-peer-urls http://etcd1:2380 --listen-peer-urls http://0.0.0.0:2380 --initial-cluster-token etcd-cluster --initial-cluster etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380 --initial-cluster-state new --enable-v2
    networks:
      - tarantooldb_network
    ports:
      - "2379:2379"
  etcd2:
    image: quay.io/coreos/etcd:v3.4.0
    command: etcd --name etcd2 --advertise-client-urls http://etcd2:2379 --listen-client-urls http://0.0.0.0:2379 --initial-advertise-peer-urls http://etcd2:2380 --listen-peer-urls http://0.0.0.0:2380 --initial-cluster-token etcd-cluster --initial-cluster etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380 --initial-cluster-state new --enable-v2
    networks:
      - tarantooldb_network
  etcd3:
    image: quay.io/coreos/etcd:v3.4.0
    command: etcd --name etcd3 --advertise-client-urls http://etcd3:2379 --listen-client-urls http://0.0.0.0:2379 --initial-advertise-peer-urls http://etcd3:2380 --listen-peer-urls http://0.0.0.0:2380 --initial-cluster-token etcd-cluster --initial-cluster etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380 --initial-cluster-state new --enable-v2
    networks:
      - tarantooldb_network

  init_host:
    image: tarantooldb:latest
    networks:
      - tarantooldb_network
    volumes:
      - ./:/usr/share/tarantool/stand
    depends_on:
      - etcd1
      - etcd2
      - etcd3
      - tarantool-router-1
      - tarantool-storage-1
    working_dir: /usr/share/tarantool/stand
    command: /bin/sh -c "\
      sleep 3 \
      && SRC_FILE=config.yml DST_FILE=/tmp/config.tcm.yml tarantool /usr/share/tarantool/tarantooldb/tools/make_config_tcm_yml.lua
      && tt cluster publish http://etcd1:2379/tdb /tmp/config.tcm.yml \
      && tt migrations publish http://etcd1:2379/tdb migrations \
      && tt migrations up http://etcd1:2379/tdb --tarantool-cluster-username=admin --tarantool-cluster-password=secret-cluster-cookie \
      && tcm add-cluster -n="Tarantool DB" -d="Example cluster" --storage.provider=etcd --storage.etcd.endpoints="http://etcd1:2379" --storage.etcd.endpoints="http://etcd2:2379" --storage.etcd.endpoints="http://etcd3:2379" --storage.etcd.prefix="/tdb" --tarantool.username="admin" --tarantool.password="secret-cluster-cookie" \
      && echo Done."

  tcm-1:
    image: tarantooldb:latest
    networks:
      - tarantooldb_network
    ports:
      - "8081:8080"
    volumes:
      - ./tcm.yml:/usr/share/tarantool/tarantooldb/tcm.yml
    depends_on:
      - init_host
    working_dir: /usr/share/tarantool/tarantooldb/
    environment:
      - TCM_SECURITY_BOOTSTRAP_API_TOKEN=admin-token
    command: ./tcm -c tcm.yml

  failover-coordinator-1:
    image: tarantooldb:latest
    networks:
      - tarantooldb_network
    volumes:
      - ./config.yml:/usr/share/tarantool/tarantooldb/config.yml
    depends_on:
      - init_host
    working_dir: /usr/share/tarantool/tarantooldb/
    command: tarantool --failover -c config.yml

networks:
  tarantooldb_network:
    driver: bridge
