version: '3'
services:
  tarantool-storage1:
    image: tarantooldb:2x-latest
    networks:
      - tarantooldb_network
    ports:
      - "8081:8081"
      - "3301:3301"
    environment:
      - TARANTOOL_INSTANCE_NAME=storage1
      - TARANTOOL_ADVERTISE_URI=tarantool-storage1:3301
      - TARANTOOL_CLUSTER_COOKIE=secret
      - TARANTOOL_HTTP_PORT=8081
  tarantool-db-init:
    image: tarantooldb:2x-latest
    networks:
      - tarantooldb_network
    environment:
      - TARANTOOLDB_TARGET_URI=tarantool-router1:8081
    working_dir: /usr/share/tarantool/tarantooldb/client/utils/
    command: /bin/bash -c "./bootstrap.sh && ./health_check.sh && ./migrate.sh"
    depends_on:
      - tarantool-storage1
    volumes:
      - ./bootstrap/:/bootstrap/
networks:
  tarantooldb_network:
