services:
  tarantool-router-msk:
    image: tarantooldb:aeon-latest
    networks:
      - tarantooldb_network
    ports:
      - "3301:3301"
    environment:
      - TT_INSTANCE_NAME=router-msk
      - TT_CONFIG_ETCD_ENDPOINTS=http://etcd1:2379,http://etcd2:2379,http://etcd3:2379
      - TT_CONFIG_ETCD_PREFIX=/tdb
      - TT_CONFIG_ETCD_HTTP_REQUEST_TIMEOUT=3
  tarantool-router-spb:
    image: tarantooldb:aeon-latest
    networks:
      - tarantooldb_network
    ports:
      - "3302:3301"
    environment:
      - TT_INSTANCE_NAME=router-spb
      - TT_CONFIG_ETCD_ENDPOINTS=http://etcd1:2379,http://etcd2:2379,http://etcd3:2379
      - TT_CONFIG_ETCD_PREFIX=/tdb
      - TT_CONFIG_ETCD_HTTP_REQUEST_TIMEOUT=3
  tarantool-storage-1-msk:
    image: tarantooldb:aeon-latest
    networks:
      - tarantooldb_network
    ports:
      - "3303:3301"
    environment:
      - TT_INSTANCE_NAME=storage-1-msk
      - TT_CONFIG_ETCD_ENDPOINTS=http://etcd1:2379,http://etcd2:2379,http://etcd3:2379
      - TT_CONFIG_ETCD_PREFIX=/tdb
      - TT_CONFIG_ETCD_HTTP_REQUEST_TIMEOUT=3
  tarantool-storage-1-spb:
    image: tarantooldb:aeon-latest
    networks:
      - tarantooldb_network
    ports:
      - "3304:3301"
    environment:
      - TT_INSTANCE_NAME=storage-1-spb
      - TT_CONFIG_ETCD_ENDPOINTS=http://etcd1:2379,http://etcd2:2379,http://etcd3:2379
      - TT_CONFIG_ETCD_PREFIX=/tdb
      - TT_CONFIG_ETCD_HTTP_REQUEST_TIMEOUT=3
  tarantool-storage-1-brn:
    image: tarantooldb:aeon-latest
    networks:
      - tarantooldb_network
    ports:
      - "3305:3301"
    environment:
      - TT_INSTANCE_NAME=storage-1-brn
      - TT_CONFIG_ETCD_ENDPOINTS=http://etcd1:2379,http://etcd2:2379,http://etcd3:2379
      - TT_CONFIG_ETCD_PREFIX=/tdb
      - TT_CONFIG_ETCD_HTTP_REQUEST_TIMEOUT=3
  tarantool-storage-2-msk:
    image: tarantooldb:aeon-latest
    networks:
      - tarantooldb_network
    ports:
      - "3306:3301"
    environment:
      - TT_INSTANCE_NAME=storage-2-msk
      - TT_CONFIG_ETCD_ENDPOINTS=http://etcd1:2379,http://etcd2:2379,http://etcd3:2379
      - TT_CONFIG_ETCD_PREFIX=/tdb
      - TT_CONFIG_ETCD_HTTP_REQUEST_TIMEOUT=3
  tarantool-storage-2-spb:
    image: tarantooldb:aeon-latest
    networks:
      - tarantooldb_network
    ports:
      - "3307:3301"
    environment:
      - TT_INSTANCE_NAME=storage-2-spb
      - TT_CONFIG_ETCD_ENDPOINTS=http://etcd1:2379,http://etcd2:2379,http://etcd3:2379
      - TT_CONFIG_ETCD_PREFIX=/tdb
      - TT_CONFIG_ETCD_HTTP_REQUEST_TIMEOUT=3
  tarantool-storage-2-brn:
    image: tarantooldb:aeon-latest
    networks:
      - tarantooldb_network
    ports:
      - "3308:3301"
    environment:
      - TT_INSTANCE_NAME=storage-2-brn
      - TT_CONFIG_ETCD_ENDPOINTS=http://etcd1:2379,http://etcd2:2379,http://etcd3:2379
      - TT_CONFIG_ETCD_PREFIX=/tdb
      - TT_CONFIG_ETCD_HTTP_REQUEST_TIMEOUT=3
  tarantool-manager-msk:
    image: tarantooldb:aeon-latest
    networks:
      - tarantooldb_network
    ports:
      - "3309:3301"
    environment:
      - TT_INSTANCE_NAME=manager-msk
      - TT_CONFIG_ETCD_ENDPOINTS=http://etcd1:2379,http://etcd2:2379,http://etcd3:2379
      - TT_CONFIG_ETCD_PREFIX=/tdb
      - TT_CONFIG_ETCD_HTTP_REQUEST_TIMEOUT=3
  tarantool-manager-spb:
    image: tarantooldb:aeon-latest
    networks:
      - tarantooldb_network
    ports:
      - "3310:3301"
    environment:
      - TT_INSTANCE_NAME=manager-spb
      - TT_CONFIG_ETCD_ENDPOINTS=http://etcd1:2379,http://etcd2:2379,http://etcd3:2379
      - TT_CONFIG_ETCD_PREFIX=/tdb
      - TT_CONFIG_ETCD_HTTP_REQUEST_TIMEOUT=3
  tarantool-manager-brn:
    image: tarantooldb:aeon-latest
    networks:
      - tarantooldb_network
    ports:
      - "3311:3301"
    environment:
      - TT_INSTANCE_NAME=manager-brn
      - TT_CONFIG_ETCD_ENDPOINTS=http://etcd1:2379,http://etcd2:2379,http://etcd3:2379
      - TT_CONFIG_ETCD_PREFIX=/tdb
      - TT_CONFIG_ETCD_HTTP_REQUEST_TIMEOUT=3

networks:
  tarantooldb_network:
    external: true
