global:
  scrape_interval: 2s
  scrape_timeout: 1s

scrape_configs:
  - job_name: "tarantool"
    static_configs:
      - targets: ["tcm-1:8080"]
    metrics_path: "/api/metrics/00000000-0000-0000-0000-000000000000"
    bearer_token: admin-token
