[agent]
    debug = true

[[inputs.http]]
    urls = [
        "http://tarantool-router1:8081/myapp/metrics",
        "http://tarantool-router2:8081/myapp/metrics",
        "http://tarantool-storage1:8081/myapp/metrics",
        "http://tarantool-storage2:8081/myapp/metrics",
        "http://tarantool-storage3:8081/myapp/metrics",
        "http://tarantool-storage4:8081/myapp/metrics"
    ]
    timeout = "30s"
    tag_keys = [
        "metric_name",
        "label_pairs_alias",
        "label_pairs_quantile",
        "label_pairs_path",
        "label_pairs_method",
        "label_pairs_status",
        "label_pairs_operation",
        "label_pairs_level",
        "label_pairs_id",
        "label_pairs_engine",
        "label_pairs_name",
        "label_pairs_index_name",
        "label_pairs_delta",
        "label_pairs_stream",
        "label_pairs_thread",
        "label_pairs_kind"
    ]
    insecure_skip_verify = true
    interval = "10s"
    data_format = "json"
    name_prefix = "tnt_"
    fieldpass = ["value"]

[[outputs.influxdb]]
    urls = ["http://influxdb:8086"]
    database = "tarantool"
    username = ""
    password = ""
    insecure_skip_verify = false
#    skip_database_creation = true
#    username = "telegraf"
#    password = "telegraf"

